import jsPDF from 'jspdf';
import { PlacementDrive } from '../types';

type RGB = [number, number, number];

const C: Record<string, RGB> = {
  emerald:   [5,  150, 105],
  emeraldBg: [236,253,245],
  dark:      [17,  24,  39],
  mid:       [75,  85,  99],
  light:     [156,163,175],
  white:     [255,255,255],
  bg:        [248,250,252],
  border:    [226,232,240],
};

function filledRect(doc: jsPDF, x: number, y: number, w: number, h: number, color: RGB, radius = 2) {
  doc.setFillColor(color[0], color[1], color[2]);
  doc.roundedRect(x, y, w, h, radius, radius, 'F');
}

function sectionHeader(doc: jsPDF, label: string, y: number, pageWidth: number): number {
  const margin = 15;
  const w = pageWidth - margin * 2;
  filledRect(doc, margin, y, w, 7, C.emeraldBg);
  doc.setDrawColor(C.emerald[0], C.emerald[1], C.emerald[2]);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, w, 7, 2, 2, 'S');
  filledRect(doc, margin, y, 2.5, 7, C.emerald, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(C.emerald[0], C.emerald[1], C.emerald[2]);
  doc.text(label.toUpperCase(), margin + 6, y + 4.6);
  return y + 10;
}

function checkY(doc: jsPDF, y: number, needed: number, pageHeight: number): number {
  if (y + needed > pageHeight - 18) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function generateJobDescriptionPdf(drive: PlacementDrive) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin     = 15;
  const contentW   = pageWidth - margin * 2;
  let y            = 0;

  // HEADER BAND
  filledRect(doc, 0, 0, pageWidth, 44, C.emerald, 0);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(drive.companyName, margin, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(209, 250, 229);
  doc.text(drive.jobTitle, margin, 23);

  const pills = [drive.positionType, drive.workMode, drive.location, `Rs. ${drive.ctcLpa} LPA`].filter(Boolean);
  let px = margin;
  pills.forEach((pill) => {
    const tw = doc.getTextWidth(pill) + 6;
    filledRect(doc, px, 25.5, tw, 6, [0, 120, 80], 1.5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(pill, px + 3, 29.8);
    px += tw + 3;
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(167, 243, 208);
  const postedText   = `Posted: ${drive.postedDate || 'N/A'}`;
  const deadlineText = `Deadline: ${drive.deadlineDate || 'N/A'}`;
  doc.text(postedText,   pageWidth - margin - doc.getTextWidth(postedText), 34);
  doc.text(deadlineText, pageWidth - margin - doc.getTextWidth(deadlineText), 39.5);

  filledRect(doc, 0, 44, pageWidth, 7, C.bg, 0);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(C.light[0], C.light[1], C.light[2]);
  doc.text('Generated by Campus Placement Portal  |  Official Job Description Document', margin, 48.5);
  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  doc.text(dateStr, pageWidth - margin - doc.getTextWidth(dateStr), 48.5);

  y = 58;

  // SECTION 1: OVERVIEW
  y = sectionHeader(doc, '01  Opening Overview', y, pageWidth);
  const col1x = margin + 2;
  const col2x = margin + contentW / 2 + 2;

  const gridRows: [string, string, string, string][] = [
    ['Job Function',  drive.jobFunction || '-',  'Job Sector',  drive.sector || '-'],
    ['Work Mode',     drive.workMode,             'Position',    drive.positionType],
    ['Location',      drive.location || '-',      'CTC Package', `Rs. ${drive.ctcLpa} LPA`],
  ];
  if (drive.stipendMonthly) {
    gridRows.push(['Monthly Stipend', `Rs. ${drive.stipendMonthly}`, 'Probation Period', drive.probationPeriodMonths ? `${drive.probationPeriodMonths} months` : '-']);
  }

  gridRows.forEach(([k1, v1, k2, v2]) => {
    y = checkY(doc, y, 10, pageHeight);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(C.light[0], C.light[1], C.light[2]);
    doc.text(k1, col1x, y);
    doc.text(k2, col2x, y);
    y += 3.5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
    doc.text(v1, col1x, y);
    doc.text(v2, col2x, y);
    y += 6;
  });

  if (drive.compensationDetails) {
    y = checkY(doc, y, 16, pageHeight);
    y += 3;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(C.light[0], C.light[1], C.light[2]);
    doc.text('COMPENSATION BREAKDOWN', col1x, y);
    y += 4;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
    doc.splitTextToSize(drive.compensationDetails, contentW - 4).forEach((line: string) => {
      y = checkY(doc, y, 6, pageHeight);
      doc.text(line, col1x, y);
      y += 5;
    });
  }
  y += 6;

  // SECTION 2: DESCRIPTION
  if (drive.description) {
    y = checkY(doc, y, 20, pageHeight);
    y = sectionHeader(doc, '02  About the Role & Responsibilities', y, pageWidth);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(C.mid[0], C.mid[1], C.mid[2]);
    doc.splitTextToSize(drive.description, contentW - 4).forEach((line: string) => {
      y = checkY(doc, y, 6, pageHeight);
      doc.text(line, margin + 2, y);
      y += 5.3;
    });
    y += 6;
  }

  // SECTION 3: REQUIREMENTS
  if (drive.requirements && drive.requirements.length > 0) {
    y = checkY(doc, y, 20, pageHeight);
    y = sectionHeader(doc, '03  Key Skill Requirements', y, pageWidth);
    drive.requirements.forEach((req) => {
      y = checkY(doc, y, 8, pageHeight);
      doc.setFillColor(C.emerald[0], C.emerald[1], C.emerald[2]);
      doc.circle(margin + 3.5, y - 1.5, 1.1, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
      doc.splitTextToSize(req, contentW - 12).forEach((line: string) => {
        y = checkY(doc, y, 6, pageHeight);
        doc.text(line, margin + 7, y);
        y += 5.2;
      });
    });
    y += 6;
  }

  // SECTION 4: ELIGIBILITY
  const elig = drive.eligibility;
  if (elig) {
    y = checkY(doc, y, 30, pageHeight);
    y = sectionHeader(doc, '04  Eligibility Criteria', y, pageWidth);
    const eligRows: [string, string][] = [
      ['Allowed Branches',     (elig.allowedBranches || []).join(', ') || '-'],
      ['Minimum CGPA',         elig.minCgpa ? String(elig.minCgpa) : '-'],
      ['10th % Required',      elig.minTenthPercentage ? `>= ${elig.minTenthPercentage}%` : '-'],
      ['12th % Required',      elig.minTwelfthPercentage ? `>= ${elig.minTwelfthPercentage}%` : '-'],
      ['Max Active Backlogs',  `${elig.maxActiveBacklogs || 0}`],
      ['Max History Backlogs', `${elig.maxHistoryBacklogs || 0}`],
      ['Max Gap Years',        `${elig.maxGapYears || 0} year(s)`],
      ['Allowed Categories',   (elig.allowedCategories || []).join(', ') || 'All'],
      ['Max Existing Offers',  String(elig.maxExistingOffers ?? 1)],
    ];
    for (let i = 0; i < eligRows.length; i += 2) {
      y = checkY(doc, y, 13, pageHeight);
      const [k1, v1] = eligRows[i];
      const [k2, v2] = eligRows[i + 1] || ['', ''];
      filledRect(doc, margin, y - 3.5, contentW / 2 - 2, 11, C.bg, 1.5);
      if (k2) filledRect(doc, margin + contentW / 2 + 1, y - 3.5, contentW / 2 - 2, 11, C.bg, 1.5);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(C.light[0], C.light[1], C.light[2]);
      doc.text(k1, margin + 3.5, y);
      if (k2) doc.text(k2, margin + contentW / 2 + 4.5, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
      doc.text(v1, margin + 3.5, y + 4.5);
      if (v2) doc.text(v2, margin + contentW / 2 + 4.5, y + 4.5);
      y += 13;
    }
    y += 4;
  }

  // SECTION 5: HIRING WORKFLOW
  if (drive.stages && drive.stages.length > 0) {
    y = checkY(doc, y, 20, pageHeight);
    y = sectionHeader(doc, '05  Hiring Process & Evaluation Rounds', y, pageWidth);
    drive.stages.forEach((stage, idx) => {
      y = checkY(doc, y, 18, pageHeight);
      filledRect(doc, margin, y - 4.5, 8, 8, C.emeraldBg, 4);
      doc.setDrawColor(C.emerald[0], C.emerald[1], C.emerald[2]);
      doc.setLineWidth(0.5);
      doc.roundedRect(margin, y - 4.5, 8, 8, 4, 4, 'S');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(C.emerald[0], C.emerald[1], C.emerald[2]);
      const numStr = String(idx + 1);
      doc.text(numStr, margin + (8 - doc.getTextWidth(numStr)) / 2, y + 0.5);

      if (idx < drive.stages.length - 1) {
        doc.setDrawColor(C.border[0], C.border[1], C.border[2]);
        doc.setLineWidth(0.5);
        doc.line(margin + 4, y + 3.5, margin + 4, y + 13);
      }

      let sy = y;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
      doc.text(stage.name, margin + 12, sy);
      sy += 5;

      if (stage.scheduledDate) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(C.light[0], C.light[1], C.light[2]);
        doc.text(`Scheduled: ${stage.scheduledDate}`, margin + 12, sy);
        sy += 4.5;
      }
      if (stage.venueOrLink) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(C.mid[0], C.mid[1], C.mid[2]);
        doc.splitTextToSize(stage.venueOrLink, contentW - 16).forEach((line: string) => {
          doc.text(line, margin + 12, sy);
          sy += 4.5;
        });
      }
      if (stage.notes) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(7.5);
        doc.setTextColor(C.light[0], C.light[1], C.light[2]);
        doc.splitTextToSize(`Note: ${stage.notes}`, contentW - 16).forEach((line: string) => {
          doc.text(line, margin + 12, sy);
          sy += 4;
        });
      }
      y = sy + 5;
    });
  }

  // SECTION 6: REQUIRED DOCUMENTS
  if (drive.requiredDocuments && drive.requiredDocuments.length > 0) {
    y = checkY(doc, y, 20, pageHeight);
    y = sectionHeader(doc, '06  Required Documents', y, pageWidth);
    drive.requiredDocuments.forEach((docItem, i) => {
      y = checkY(doc, y, 9, pageHeight);
      if (i % 2 === 0) filledRect(doc, margin, y - 3.5, contentW, 9, C.bg, 1.5);
      filledRect(doc, margin + 2, y - 2.5, 5, 5, C.emerald, 1.2);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text('v', margin + 3.5, y + 1.2);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(C.dark[0], C.dark[1], C.dark[2]);
      doc.text(docItem, margin + 10, y + 0.8);
      y += 9;
    });
    y += 4;
  }

  // SECTION 7: IMPORTANT NOTICE
  if (drive.importantNotice) {
    y = checkY(doc, y, 24, pageHeight);
    filledRect(doc, margin, y, contentW, 24, [255, 251, 235], 2);
    doc.setDrawColor(253, 186, 0);
    doc.setLineWidth(0.4);
    doc.roundedRect(margin, y, contentW, 24, 2, 2, 'S');
    filledRect(doc, margin, y, 3.5, 24, [245, 158, 11], 0);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(146, 64, 14);
    doc.text('IMPORTANT NOTICE', margin + 7, y + 7);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(120, 53, 15);
    doc.splitTextToSize(drive.importantNotice, contentW - 14).slice(0, 2).forEach((line: string, li: number) => {
      doc.text(line, margin + 7, y + 14 + li * 5.5);
    });
    y += 29;
  }

  // SECTION 8: EXTERNAL LINKS
  const hasLinks = (drive.thirdPartyLinks && drive.thirdPartyLinks.length > 0) || drive.externalApplyUrl;
  if (hasLinks) {
    y = checkY(doc, y, 20, pageHeight);
    y = sectionHeader(doc, '07  External Links & Resources', y, pageWidth);
    if (drive.externalApplyUrl) {
      y = checkY(doc, y, 10, pageHeight);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(C.mid[0], C.mid[1], C.mid[2]);
      doc.text('External Apply URL:', margin + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(37, 99, 235);
      doc.text(drive.externalApplyUrl, margin + 2, y + 5.5);
      y += 13;
    }
    if (drive.thirdPartyLinks) {
      drive.thirdPartyLinks.forEach((link) => {
        y = checkY(doc, y, 10, pageHeight);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(C.mid[0], C.mid[1], C.mid[2]);
        doc.text(`${link.label || 'Link'}:`, margin + 2, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(37, 99, 235);
        doc.text(link.url, margin + 2, y + 5.5);
        y += 13;
      });
    }
  }

  // FOOTER on every page
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    const ph = doc.internal.pageSize.getHeight();
    filledRect(doc, 0, ph - 13, pageWidth, 13, C.emerald, 0);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(
      'Campus Placement Management Portal  |  Official Job Description  |  Confidential',
      margin, ph - 5.5
    );
    const pageLabel = `Page ${p} of ${totalPages}`;
    doc.text(pageLabel, pageWidth - margin - doc.getTextWidth(pageLabel), ph - 5.5);
  }

  const fileName = `JD_${drive.companyName.replace(/\s+/g, '_')}_${drive.jobTitle.replace(/\s+/g, '_')}.pdf`;
  doc.save(fileName);
}
